// Citas del checador original del cliente — misma cita todo el día, cambia a diario.
export interface Quote { texto: string; autor: string }

export const QUOTES_ENTRADA: Quote[] = [
  { texto: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", autor: "Albert Schweitzer" },
  { texto: "Cada mañana tenemos dos opciones: seguir durmiendo con tus sueños, o levantarte y perseguirlos.", autor: "Anónimo" },
  { texto: "El trabajo duro supera al talento cuando el talento no trabaja duro.", autor: "Tim Notke" },
  { texto: "No cuentes los días, haz que los días cuenten.", autor: "Muhammad Ali" },
  { texto: "La única forma de hacer un gran trabajo es amar lo que haces.", autor: "Steve Jobs" },
  { texto: "El secreto para salir adelante es empezar.", autor: "Mark Twain" },
  { texto: "Cree que puedes y ya estás a mitad del camino.", autor: "Theodore Roosevelt" },
  { texto: "Todo parece imposible hasta que se hace.", autor: "Nelson Mandela" },
  { texto: "El único modo de hacer un gran trabajo es poner el corazón en lo que haces.", autor: "Steve Jobs" },
  { texto: "El esfuerzo de hoy es el éxito de mañana.", autor: "Anónimo" },
  { texto: "Sé el cambio que deseas ver en el mundo.", autor: "Mahatma Gandhi" },
  { texto: "No te rindas. El comienzo siempre es lo más difícil.", autor: "Anónimo" },
  { texto: "Una meta sin un plan es solo un deseo.", autor: "Antoine de Saint-Exupéry" },
  { texto: "El talento gana partidos, pero el trabajo en equipo gana campeonatos.", autor: "Michael Jordan" },
  { texto: "Haz hoy lo que otros no harán y mañana tendrás lo que otros no tienen.", autor: "Jerry Rice" },
  { texto: "La disciplina es el puente entre metas y logros.", autor: "Jim Rohn" },
  { texto: "Pequeños progresos diarios llevan a grandes resultados.", autor: "Satya Nadellas" },
  { texto: "Tu actitud determina tu dirección.", autor: "Anónimo" },
  { texto: "Cada día es una nueva oportunidad para cambiar tu vida.", autor: "Anónimo" },
  { texto: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor: "Robert Collier" },
  { texto: "No esperes el momento perfecto, toma el momento y hazlo perfecto.", autor: "Zoey Sayward" },
  { texto: "Empieza donde estás, usa lo que tienes, haz lo que puedas.", autor: "Arthur Ashe" },
  { texto: "Los ganadores no hacen cosas diferentes, hacen las cosas de manera diferente.", autor: "Shiv Khera" },
  { texto: "Trabaja duro en silencio. Deja que tu éxito haga el ruido.", autor: "Frank Ocean" },
  { texto: "Cada experto fue una vez un principiante.", autor: "Helen Hayes" },
  { texto: "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.", autor: "Proverbio chino" },
  { texto: "La vida es 10% lo que te pasa y 90% cómo reaccionas.", autor: "Charles R. Swindoll" },
  { texto: "No tienes que ser brillante para empezar, pero tienes que empezar para ser brillante.", autor: "Zig Ziglar" },
  { texto: "El éxito es caminar de fracaso en fracaso sin perder el entusiasmo.", autor: "Winston Churchill" },
  { texto: "Grandes logros requieren grandes riesgos.", autor: "Heráclito" },
  { texto: "No te limites. Muchas personas se limitan a lo que piensan que pueden hacer.", autor: "Mary Kay Ash" },
];

export const QUOTES_SALIDA: Quote[] = [
  { texto: "Al final del día puedes estar satisfecho de lo que lograste hoy.", autor: "Anónimo" },
  { texto: "El descanso no es ociosidad. Es necesario para que la mente y el cuerpo recarguen fuerzas.", autor: "John Lubbock" },
  { texto: "Cuídate bien. Eres la única persona que cargará tu cuerpo toda la vida.", autor: "Anónimo" },
  { texto: "La familia es lo más importante. Disfruta cada momento con ellos.", autor: "Anónimo" },
  { texto: "Un buen descanso es parte del trabajo bien hecho.", autor: "Anónimo" },
  { texto: "El equilibrio entre trabajo y vida personal no es un lujo, es una necesidad.", autor: "Anónimo" },
  { texto: "Termina el día con gratitud. Siempre hubo algo bueno en él.", autor: "Zig Ziglar" },
  { texto: "Recarga energías. Mañana es otro día lleno de posibilidades.", autor: "Anónimo" },
  { texto: "Hoy diste lo mejor de ti. Eso siempre es suficiente.", autor: "Anónimo" },
  { texto: "El descanso y la alegría son el combustible del mañana.", autor: "Anónimo" },
  { texto: "Comparte tu sonrisa con el mundo. Es un símbolo de amistad y paz.", autor: "Christie Brinkley" },
  { texto: "Lo que hagas hoy puede mejorar todos tus mañanas.", autor: "Ralph Marston" },
  { texto: "Cuida tu cuerpo. Es el único lugar que tienes para vivir.", autor: "Jim Rohn" },
  { texto: "La felicidad no se encuentra al final del camino. Está en el camino mismo.", autor: "Anónimo" },
  { texto: "Cada paso cuenta. Celebra lo que lograste hoy.", autor: "Anónimo" },
  { texto: "El tiempo con tu familia es sagrado. Valóralo.", autor: "Anónimo" },
  { texto: "No importa qué tan lento vayas, siempre y cuando no te detengas.", autor: "Confucio" },
  { texto: "El éxito es disfrutar el camino, no solo llegar a la meta.", autor: "Anónimo" },
  { texto: "Mañana es otra oportunidad para hacerlo mejor.", autor: "Anónimo" },
  { texto: "Descansa. Dios también descansó el séptimo día.", autor: "Anónimo" },
  { texto: "La gratitud convierte lo que tenemos en suficiente.", autor: "Melody Beattie" },
  { texto: "Vive cada día como si fuera una segunda oportunidad.", autor: "Anónimo" },
  { texto: "El hogar es donde está el corazón.", autor: "Plinio el Viejo" },
  { texto: "La mejor inversión que puedes hacer es en ti mismo.", autor: "Warren Buffett" },
  { texto: "Respira profundo. Hoy fue un buen día.", autor: "Anónimo" },
  { texto: "Ríe mucho, ama mucho y deja el resto al tiempo.", autor: "Anónimo" },
  { texto: "El momento presente siempre será.", autor: "Eckhart Tolle" },
  { texto: "Sé amable contigo mismo. Eres hijo del universo.", autor: "Max Ehrmann" },
  { texto: "La vida es demasiado corta para no disfrutar cada momento.", autor: "Anónimo" },
  { texto: "Haz del descanso un hábito, no una recompensa.", autor: "Anónimo" },
  { texto: "Lo mejor está por venir. Descansa y prepárate para recibirlo.", autor: "Anónimo" },
];
